### ISSUE TITLE
Zoom to current location is not smooth

### ISSUE THREAD

**Issue by konishon** [igaurab/user_location_plugin#26]
**Describe the bug**
On pressing zoom to current location widget, the camera jumps to current location

**To Reproduce**
1. Load map
2. Tap on zoom to currect location widget

**Expected behavior**
The camera should smoothly animate to current user location

**Desktop (please complete the following information):**
N.A

**Smartphone (please complete the following information):**
- Andorid Emulator

**Additional context**
N.A.

**Comment by igaurab** [comment]
That is because, I have not used animation there, will fix it.

**Comment by igaurab** [comment]
So the issue is:
Whenever the `updateMapLocationOnPositionChange` is set to false, the animation runs perfectly.
But whenever the `updateMapLocationOnPositionChange` is set to true, the two `mapController` interfare with each other and hence the animation is not  rendered properly.

The workaround:
1. when FAB is clicked, set `updateMapLocationOnPositionChange = false`
2. call the animation
3. when the animation is finished or dismissed set `updateMapLocationOnPositionChange = true`
