### ISSUE TITLE
E/EventChannel#locationStatusStream(25617): Failed to close existing event stream

### ISSUE THREAD

**Issue by amokio** [igaurab/user_location_plugin#37]
```
E/EventChannel#locationStatusStream(25617): Failed to close existing event stream
E/EventChannel#locationStatusStream(25617): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter p0
E/EventChannel#locationStatusStream(25617): 	at com.example.user_location.UserLocationPlugin$Companion$registerWith$1.onCancel(Unknown Source:2)
E/EventChannel#locationStatusStream(25617): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:187)
E/EventChannel#locationStatusStream(25617): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:172)
E/EventChannel#locationStatusStream(25617): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/EventChannel#locationStatusStream(25617): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/EventChannel#locationStatusStream(25617): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#locationStatusStream(25617): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/EventChannel#locationStatusStream(25617): 	at android.os.Looper.loop(Looper.java:174)
E/EventChannel#locationStatusStream(25617): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/EventChannel#locationStatusStream(25617): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#locationStatusStream(25617): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/EventChannel#locationStatusStream(25617): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by amokio** [comment]
@igaurab

**Comment by antonbt** [comment]
I have the same issue when navigating to some other widget and back again.. It would be nice to have some control over the actual location listener in order to cancel, pause or resume it manually,

Furthermore the plugin is filling up the log with some "Direction" output. I am guessing some debug flag is turned on.

`I/flutter (  340): Direction : 40.6218478598268
I/flutter (  340): Direction : 40.6218478598268
I/flutter (  340): Direction : 40.6218478598268
I/flutter (  340): Direction : 40.6218478598268
I/flutter (  340): Direction : 40.6218478598268
I/flutter (  340): Direction : 40.6218478598268
I/flutter (  340): Direction : 40.6218478598268
I/flutter (  340): Direction : 40.6218478598268
I/flutter (  340): Direction : 40.6218478598268
I/flutter (  340): Direction : 40.6218478598268
I/flutter (  340): Direction : 40.6218478598268
I/flutter (  340): Direction : 40.6218478598268
I/flutter (  340): Direction : 40.6218478598268
I/flutter (  340): Direction : 40.6218478598268
I/flutter (  340): Direction : 40.6218478598268
I/flutter (  340): Direction : 40.6218478598268
I/flutter (  340): Direction : 40.6218478598268
I/flutter (  340): Direction : 40.6218478598268`

**Comment by xni06** [comment]
The logging issue has already been merged #40

**Comment by xni06** [comment]
Take a look at https://github.com/igaurab/user_location_plugin/pull/41 that should fix the `IllegalArgumentException`. You can pull in this version by using the following in your `pubspec.yaml`

```
  user_location:
    git:
      url: "https://github.com/xni06/user_location_plugin.git"
      ref: "5855345d5b3a87cebd3be525a238278f5dfdca76"
```

Once it's merged, please reference `https://github.com/igaurab/user_location_plugin.git` instead

**Comment by lucygeneric** [comment]
good fix @xni06 - works well thanks

**Comment by xni06** [comment]
@mattia-lau you can now close this issue
